### ISSUE TITLE
Teclado piifox er75

### ISSUE THREAD

**Issue by Diegogregodasilva12** [qmk/qmk.fm#5]
### Information

- [X] None of the other issue templates apply

### Description

Hoje tentei atualizar os drivers do meu novo teclado da marca piifox modelo er75 seguindo as orientações do manual do usuário entrei no endereço app.qmk.top segui as orientações o site achou meu modelo de teclado e me sugeriu uma atualização! Cliquei em atualizar o processo iniciou o teclado apagou todas as luzes e a página ficou em branco! Isso já tem mais de 6 horas! O teclado não liga e a página não atualiza de maneira nenhuma! Preciso de ajuda!

**Comment by zvecr** [comment]
This is not the repo to be opening issues related to keyboards.
